#!/bin/bash

demo(){
	echo "

	$0 demo
		Demo and Help Menu
	
	$0 b | blacklist
		add blacklist for ARC Driver

	$0 c | connect
		manual connect for usb and raw

	$0 t | test
		do everything and test command

	"
}

blacklist(){
	echo -e "blacklist nfc\nblacklist pn533\nblacklist pn533_usb" | sudo tee -a /etc/modprobe.d/blacklist-pn533.conf
	sudo modprobe -r pn533_usb
	sudo modprobe -r pn533
	sudo modprobe -r nfc
	sudo lsmob | grep -i "pn533"
}

connect(){
	snap connect cryptnox:hardware-observe
	snap connect cryptnox:raw-usb
	snap restart cryptnox
	snap connections cryptnox
	snap services cryptnox
}

demo-try(){
	blacklist
	connect
	cryptnox.python --version
	echo -e "\n" 
	sleep 1
	cryptnox.pscs-scan
	echo -e "\n" 
	sleep 1
	cryptnox.card
}


case $1 in 

	h|help) 
		demo
	  	;;
  	b|blacklist)
		blacklist
	 	;;
	c|connect)
		connect
		;;
	t|test)
		demo-try
		;;
	*)
		demo
esac
