stages:
- build
- publish

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  DOCKER_IMAGE: unoplatform/snapcraft:20201014-arm64
    # cache: &global_cache
    #   key: ${CI_JOB_NAME}
    #   policy: pull-push
    # snap:build:
    #   variables:
    #     RELEASE_TYPE: edge
    #   image: unoplatform/snapcraft:20201014-arm64
    #   stage: build
    #   script:
    #   - export LC_ALL=C.UTF-8
    #   - export LANG=C.UTF-8
    #   - export SNAP_ARCH=arm64
    #   - export SNAPCRAFT_BUILD_INFO=1
    #   - apt-get -y update
    #   - echo $SNAPCRAFT_LOGIN | base64 -d > snapcraft.login && snapcraft login --with snapcraft.login
    #   - snapcraft --destructive-mode
    #     #- SNAPCRAFT_SETUP_CORE=1 snapcraft --destructive-mode
    #     #- |
    #     #  if [ "$CI_COMMIT_REF_NAME" = "release" ]; then
    #     #    echo $SNAPCRAFT_LOGIN | base64 --decode --ignore-garbage > snapcraft.login
    #     #    snapcraft login --with snapcraft.login
    #     #    snapcraft push cryptnox*.snap --release edge
    #     #    snapcraft logout
    #     #  fi
    #     #  script:
    #   - snapcraft push cryptnox*.snap --release $RELEASE_TYPE
    #   - snapcraft logout && rm snapcraft.login
    #     #  rules:
    #     #- if: '$CI_COMMIT_REF_NAME == "master" && $CI_COMMIT_TAG'
    #     #  when: manual
    #   allow_failure: false
    #   artifacts:
    #     paths:
    #     - "./*.snap"
    #     expire_in: 10 days
    #   only:
    #     refs:
    #     - tags
    #     - merge_requests
    #     - web
    #     - schedules

# variables:
#   GIT_SUBMODULE_STRATEGY: recursive
# 
# variables:
#   CONTAINER_IMAGE: registry.gitlab.e.foundation:5000/e/tools/easy-installer
#   CONTAINER_TAG: stable
# 
# stages:
# - test
# - prepare
# - build
# - publish


build-ubuntu:
  stage: build
  image: unoplatform/snapcraft:20201014-arm64
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - snapcraft
    - ls
  artifacts:
    name: "cryptnox"
    paths:
      - cryptnox*.snap


publish-ubuntu:
  stage: publish
  image: unoplatform/snapcraft:20201014-arm64
  variables:
    RELEASE_TYPE: edge
  script:
    - echo ${SNAPCRAFT_LOGIN_FILE} | base64 -d > snapcraft.login && snapcraft login --with snapcraft.login
    - snapcraft push *.snap --release $RELEASE_TYPE
    - snapcraft logout && rm snapcraft.login
  rules:
    - if: '$CI_COMMIT_TAG'
      when: manual
